### ISSUE TITLE
[drawer] close 事件设计有缺陷，重复触发

### ISSUE THREAD

**Issue by fengtianze** [alauda/ui#247]

**Comment by fengtianze** [comment]
[[](url)](https://github.com/alauda/alauda-ui/compare/feat/refactor-drawer)

**Comment by JounQin** [comment]
`DrawerService` 的 Options 与 Input 个数不匹配

Service 模式打开时 Input 其实不是真的 Input，可以考虑跟 DialogService 一样处理，避免误用
