### ISSUE TITLE
aui-table 的 sticky-column 两侧的边框不显示

### ISSUE THREAD

**Issue by yangxiaolang** [alauda/ui#371]
expect:
![image](https://user-images.githubusercontent.com/24679861/185530380-8db9d226-32b0-403a-a819-dc70c004ac1d.png)

now:
![image](https://user-images.githubusercontent.com/24679861/185530475-b11783e4-138f-487e-98c2-0e61dac483d4.png)

**Comment by JounQin** [comment]
close via #372
