### ISSUE TITLE
[Dialog] 浏览器前进后退行为不会使 Dialog 关闭

### ISSUE THREAD

**Issue by yangxiaolang** [alauda/ui#514]
### 现状
在打开对话框的时候依然可以使用浏览器的前进后退功能切换页面，该行为也不会导致对话框的关闭

https://github.com/alauda/ui/assets/24679861/f5b118e8-dbf2-4565-9f5f-d58aab4465f9

### 预想处理方案
~1. 对话框阻断浏览器的前进后退行为（是否需要提示，怎么提示~
2. 对话框监听路由事件，切换路由时关闭自身（是否存在跨页面生命周期的对话框）

跟设计讨论，对话框阻塞浏览器行为不太合理，且对话框组件延用表单的阻断性提示并不合理，采用 路由切换对话框自己关闭 实现

**Comment by yangxiaolang** [comment]
直接往组件库注入 `Router` 不合理，在业务中处理

**Comment by fengtianze** [comment]
正常情况下应该业务里自己处理组件销毁时自己关闭打开的对话框。想统一处理可以在全局监听router变化，然后dialogService.cloaseAll()
